# .github/workflows/deploy.yml
name: Deploy Application

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main  #  ветка

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: "rhammatov"
        password: "89991778287"

    - name: Build and push Docker image
      run: |
        docker build -t rhammatov/vital_scope_proxy:latest .
        docker push rhammatov/vital_scope_proxy:latest

    - name: Deploy to remote server
      uses: appleboy/ssh-action@master
      with:
        host: 176.108.245.175
        username: radis
        key: ${{ secrets.SSHKEY }}
        port: 22
        script: |
          docker stop proxy-service || true
          docker rm proxy-service || true
          docker rmi rhammatov/vital_scope_proxy || true
          docker pull rhammatov/vital_scope_proxy || true
          docker run -d -ti --name proxy-service -p 8081:3000 -v /proxy:/app/proxy rhammatov/vital_scope_proxy:latest